In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('laptops.csv')
df.head(50)

,title,price,rating
0,"HP 15s, AMD Ryzen 3 5300U, 15.6 inch(39.6cm) F...","39,990",NaN
1,"Dell Vostro 3420 Laptop,12th Gen Intel Core i3...","41,990",NaN
2,"Honor MagicBook 14, AMD Ryzen 5 5500U 14-inch ...","44,490",4.4 out of 5 stars
3,HP 255 G8 Laptop with AMD Athlon Silver 3050U ...,"26,999",NaN
4,Lenovo IdeaPad Slim 3 Intel Core i3-1115G4 11t...,"33,639",NaN
5,"Lenovo Ideapad 3 AMD Ryzen 5 5500U 15.6"" (39.6...","43,917",NaN
6,(Renewed) Dell Latitude E5470 Intel Core i5 6t...,"17,920",NaN
7,"HP 15s,11th Gen Intel Core i3-1115G4 8GB RAM/5...","40,490",NaN
8,"HP 15s, 11th Gen Intel Core i3 8GB RAM/1TB HDD...","37,490",NaN
9,"Lenovo V15 AMD Ryzen 5 5500U 15.6"" (39.62cm) F...","37,999",NaN
10,"Dell Inspiron 3511 Laptop, Intel i3-1115G4, 8G...","38,990",NaN
11,Apple 2023 MacBook Pro Laptop M2 Max chip with...,"3,45,766",NaN
12,Apple 2023 MacBook Pro Laptop M2 Max chip with...,"3,09,900",NaN
13,HP Pavilion 14 12th Gen Intel Core i5 16GB RAM...,"66,990",NaN
14,Acer Extensa 15 Lightweight Laptop Intel Core ...,"42,990",NaN
15,"Lenovo V15 AMD Ryzen5 5500U 15.6"" (39.62 cm) F...","35,990",NaN
16,"Lenovo IdeaPad D330 Intel Celeron N4020 10.1"" ...","20,990",NaN
17,HP 245 G8 3S7L2PA Notebook Business Laptop 14 ...,"24,990",NaN
18,"Apple 2020 MacBook Air Laptop M1 chip, 13.3-in...","84,990",4.7 out of 5 stars
19,"Lenovo V15 Intel Celeron N4020 15.6"" (39.62 cm...","22,980",NaN
20,"Dell Vostro 3510 Laptop, Intel Pentium Gold 75...","32,590",NaN
21,Fujitsu CH Intel Evo Core i5 11th Gen 13.3â€ ...,"54,990",NaN
22,Apple 2023 MacBook Pro Laptop M2 Max chip with...,"3,49,900",NaN
23,"Dell Vostro 3420 Laptop,12th Gen Intel Core i3...","41,990",NaN
24,"HP 15s, AMD Ryzen 3 5300U, 15.6 inch(39.6cm) F...","39,990",NaN
25,"Lenovo IdeaPad Slim 1 AMD Ryzen 3 3250U 15.6"" ...","36,990",NaN
26,Xiaomi Notebook Pro QHD+IPS AntiGlare Display ...,"56,999",4.3 out of 5 stars
27,HP 15s AMD Ryzen 3-5300U 15.6inch(39.6cm) FHD ...,"37,990",NaN
28,HP 15s- Ryzen 5-5500U 8GB RAM/512GB SSD 15.6 i...,"45,490",NaN
29,Lenovo IdeaPad Slim 3 Intel Celeron N4020 4th ...,"25,685",NaN
30,Acer Extensa 15 Lightweight Laptop 11th Gen In...,"32,489",NaN
31,"ASUS VivoBook 14 (2021), Intel Core i5-1035G1 ...","42,990",NaN
32,"ASUS VivoBook 15 (2021), 15.6-inch (39.62 cm) ...","25,990",NaN
33,Apple 2023 MacBook Pro Laptop M2 Max chip with...,"3,45,766",NaN
34,Fujitsu CH Intel Evo Core i5 11th Gen 13.3â€ ...,"54,990",NaN
35,HP Victus Gaming Latest AMD Ryzen 5 5600H Proc...,"55,990",4.3 out of 5 stars
36,Lenovo IdeaPad Slim 3 Chromebook Intel Celeron...,"15,990",NaN
37,"Honor MagicBook X14, 11th Gen Intel Core i5-11...","46,990",NaN
38,"ASUS VivoBook 15, Intel Core i3-1115G4 11th Ge...","35,990",NaN
39,HP Victus Gaming Latest 12th Gen Intel Core i7...,"79,990",4.3 out of 5 stars
40,(Renewed) Dell Latitude Laptop 7390 Intel Core...,"29,393",NaN
41,RedmiBook Pro Intel Core i5 11th Gen H Series ...,NaN,NaN
42,"Dell XPS 9720 Laptop, Intel i9-12900HK, 32GB D...","3,85,578",NaN
43,"ASUS Vivobook 14, Intel Core i7-1165G7 11th Ge...","56,990",NaN
44,Xiaomi NoteBook Pro 120 12th Gen Intel i5-1245...,"64,999",NaN
45,"Dell Vostro 3420 Laptop,12th Gen Intel Core i3...","41,990",NaN
46,"HP 15s, AMD Ryzen 3 5300U, 15.6 inch(39.6cm) F...","39,990",NaN
47,Dell (Renewed) Latitude Intel E5440-i3-4 GB SS...,"15,037",NaN
48,"Dell Inspiron 3511 Laptop, Intel i3-1115G4, 8G...","38,990",NaN
49,"Lenovo V15 AMD Ryzen 3 5300U 15.6"" (39.62cm) F...","33,999",NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   339 non-null    object
 1   price   331 non-null    object
 2   rating  24 non-null     object
dtypes: object(3)
memory usage: 8.1+ KB

In [4]:
print(df.columns.tolist())

['title', 'price', 'rating']

In [5]:
def clean_price_column(price):
    if isinstance(price,str):
        price=price.replace(',','')
        price=price.strip()
        if price.isnumeric():
            price=int(price)
            return price
        if len(price)==0:
            return np.nan
    return price

In [6]:
clean_price_column('1,999')

1999

In [7]:
df['cleaned_price']=df['price'].apply(clean_price_column)

In [8]:
def clean_rating_column(rating):
    if isinstance(rating,str):
        rating=rating.split()[0]
        return float(rating)
    return rating

In [9]:
df['cleaned_rating']=df['rating'].apply(clean_rating_column)

In [10]:
df.sort_values(by='price',ascending=False,inplace=True)

In [11]:
df.drop(columns=['price','rating'],inplace=True)

In [12]:
df

,title,cleaned_price,cleaned_rating
129,"ASUS TUF Gaming A15, 15.6"" (39.62 cm) FHD 144H...",98000.0,4.3
104,"ASUS TUF Gaming A15, 15.6"" (39.62 cm) FHD 144H...",98000.0,4.3
160,"ASUS TUF Gaming A15, 15.6"" (39.62 cm) FHD 144H...",98000.0,4.3
179,Samsung Galaxy Book2 360 Intel 12th Gen i7 Evo...,97990.0,4.3
79,"ASUS ROG Strix G17, 17.3-inch (43.94 cms) FHD ...",90990.0,4.5
...,...,...,...
191,(renewed) Latitude D620 core 2 Duo Laptop/4 gb...,NaN,NaN
239,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 1...,NaN,NaN
276,(Renewed) Lenovo IdeaPad 3 11th Gen Intel Core...,NaN,NaN
301,"Dell Inspiron 3525 Laptop, AMD Athlon Silver 3...",NaN,NaN
314,(Renewed) Dell Latitude Laptop E5470 Intel Cor...,NaN,NaN